name: 'Build Container Image'

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: vincentscode
        password: ${{ secrets.GH_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/vincentscode/bunnybot:latest
        docker run ghcr.io/vincentscode/bunnybot:latest
        docker push ghcr.io/vincentscode/bunnybot:latest
